services:
  - type: web
    name: LISI_Budget
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
